/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escala;

import static escala.Escala.scaledHeight;
import static escala.Escala.scaledWidth;
import java.awt.*;
import java.awt.event.ActionListener;
import javafx.event.ActionEvent;
import javax.swing.*;
/**
 *
 * @author Barath Tirumala
 */
public class Start{
    
    private JFrame frame;
    private static int width = 900;
    private static int height = 600;
    private final static double SCALE = 1.5;
    public static int scaledWidth = (int) (width * SCALE);
    public static int scaledHeight = (int) (height * SCALE);
    JButton play = new JButton("PLAY");
    JButton set = new JButton("SETTINGS");
    JButton cred = new JButton("CREDITS");
    JButton back = new JButton("BACK");
    JButton back2 = new JButton("BACK");
    JButton exit = new JButton("EXIT");
    JPanel cards = new JPanel(new CardLayout());
    

    /**
     * Creates new form Start
     */
    public Start() {
        frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setTitle("Escala Test");
        frame.setSize( scaledWidth, scaledHeight);
        frame.setVisible(true);
        
        
        
        addIndexCard(cards);
        addDiffCard(cards);
        addSetCard(cards);
        addCredCard(cards);
        
        frame.add(cards);
        
        play.addActionListener(e -> toDiff(frame));
        back.addActionListener(e -> toMenu(frame));
        back2.addActionListener(e -> toMenu(frame));
        set.addActionListener(e -> toSet(frame));
        cred.addActionListener(e -> toCred(frame));
        exit.addActionListener(e -> quit(frame));
    
       
        frame.setVisible(true);
    }
    
    public void addIndexCard(Container pane){
        JPanel index = new JPanel();
        index.add(new JLabel("ESCALA"));
        index.add(play);
        index.add(set);
        index.add(cred);
        index.add(exit);
        
        pane.add(index, "INDEX");
        
    }    
    
    public void addDiffCard(Container pane){
        JPanel diff = new JPanel();
        diff.add(new JLabel("DIFFICULTY"));
        diff.add(new JButton("EASY"));
        diff.add(new JButton("MEDIUM"));
        diff.add(new JButton("HARD"));
        
        pane.add(diff, "DIFF");
    }
    
    public void addSetCard(Container pane){
        JPanel set = new JPanel();
        set.add(new JLabel("SETTINGS"));
        set.add(new JLabel("This page is under construction"));
        set.add(back);
        
        pane.add(set, "SET");
    }
    
    public void addCredCard(Container pane){
        JPanel cred = new JPanel();
        cred.add(new JLabel("CREDITS"));
        cred.add(new JLabel("This page is under construction"));
        cred.add(back2);
        
        pane.add(cred, "CRED");
    }
    
    
    
    
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Start game = new Start();
    }

    private void toDiff(Container parent) {
        CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, "DIFF");
    }
    
    private void toMenu(Container parent) {
        CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, "INDEX");
    }
    
    private void toSet(Container parent) {
        CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, "SET");
    }
    
    private void toCred(Container parent) {
        CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, "CRED");
    }
    private void quit(Container parent) {
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
